Updated run script

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -19,4 +19,22 @@ npm run compile
 
 # run the app
 echo ">>> Starting the app..."
-./dist/linux-armv7l-unpacked/bitfolio
+
+function dorun() {
+  # Temporarily disable the -e option
+  set +e
+  timeout 3600 ./dist/linux-armv7l-unpacked/bitfolio
+  local exit_code=$?
+  # Re-enable the -e option
+  set -e
+  # if it was a timeout, restart the app
+  if [ $exit_code -eq 124 ]; then
+    echo ">>> Restarting the app..."
+    dorun
+  elif [ $exit_code -ne 0 ]; then
+    echo ">>> App exited with error code $exit_code"
+    exit $exit_code
+  fi
+}
+
+dorun
